if(UNIX)
    if(CMAKE_SYSTEM_NAME STREQUAL "Linux")
        option(LINUX "Enable Linux target" ON)
        add_definitions(-DLINUX)
    elseif(APPLE)
        if(CMAKE_SYSTEM_NAME STREQUAL "Darwin")
            add_definitions(-DOSX)
        elseif(CMAKE_SYSTEM_NAME STREQUAL "iOS")
            add_definitions(-DIOS)
        endif()
    else()
        add_definitions(-DANDROID)
    endif()
elseif(AMUI) # for this to work, you need amui in the same folder as core and you need to add -DCMAKE_TOOLCHAIN_FILE=/../amui/cmake/amui.cmake when configuring
    #add_definitions(-DAMUI) # not needed
elseif(WIN32)
    add_definitions(-DWINDOWS)
else()
    message(FATAL_ERROR "Unsupported platform: ${CMAKE_SYSTEM_NAME}")
endif()