set(OS "UNKNOWN")
if(UNIX)
    if(CMAKE_SYSTEM_NAME STREQUAL "Linux")
        option(LINUX "Enable Linux target" ON)
        set(OS "LINUX")
        add_definitions(-DLINUX)
    elseif(APPLE)
        if(CMAKE_SYSTEM_NAME STREQUAL "Darwin")
            option(OSX "Enable OSX target" ON)
            option(MACOS "Enable MacOS target" ON)
            set(OS "OSX")
            add_definitions(-DOSX)
            add_definitions(-DMACOS)
        elseif(CMAKE_SYSTEM_NAME STREQUAL "iOS")
            option(IOS "Enable iOS target" ON)
            set(OS "IOS")
            add_definitions(-DIOS)
        endif()
    else()
        option(ANDROID "Enable Android target" ON)
        set(OS "ANDROID")
        add_definitions(-DANDROID)
    endif()
elseif(AMUI) # for this to work, you need amui in the same folder as core and you need to add -DCMAKE_TOOLCHAIN_FILE=/../amui/cmake/amui.cmake when configuring
    option(AMUI "Enable AMUI target" ON) # not needed
    set(OS "AMUI")
    add_definitions(-DAMUI) # not needed
elseif(WIN32)
    option(WINDOWS "Enable Windows target" ON)
    set(OS "WINDOWS")
    add_definitions(-DWINDOWS)
else()
    message(FATAL_ERROR "Unsupported platform: ${CMAKE_SYSTEM_NAME}")
endif()
message("-- Operating System build: ${OS}")